#!/bin/sh
echo "Post installation"

CONFIG_PO='\n[merge "pofile"]\n\tname = Gettext *.po merge driver\n\tdriver = /usr/local/bin/git-merge-po %O %A %B'
CONFIG_MO='\n[merge "mofile"]\n\tname = Gettext *.mo merge driver\n\tdriver = /usr/local/bin/git-merge-mo %O %A %B\n'

if [ ! -f /etc/gitconfig ]
then
	echo "Creating /etc/gitconfig"
	echo $CONFIG_PO > /etc/gitconfig
	echo $CONFIG_MO >> /etc/gitconfig

elif ! grep -q '\[merge "pofile"\]' /etc/gitconfig;
then
	echo "Append to /etc/gitconfig"
	echo $CONFIG_PO >> /etc/gitconfig
	echo $CONFIG_MO >> /etc/gitconfig
fi

echo "\n\tIMPORTANT NOTE"
echo "\tTo activate these custom merge drivers you'll have to create a .gitattributes file in your repository"
echo "\tAppend the following lines to your .gitattributes:"
echo "\t*.po   merge=pofile"
echo "\t*.pot  merge=pofile"
echo "\t*.mo   merge=mofile"
echo ""
echo "Done, git is configured!"

