#!/bin/sh
#echo "Pre remove"

echo "Removing /usr/local/bin/git-merge-po"
if [ -f /usr/local/bin/git-merge-po ]
then
	rm /usr/local/bin/git-merge-po
fi

# Search for 'merge "pofile"' and delete it together with the 2 consecutive lines
echo "Removing custom driver config from /etc/gitconfig"
if grep -q '\[merge "pofile"\]' /etc/gitconfig; 
then
	sed --in-place '/\[merge "pofile"\]/,+2d' /etc/gitconfig
fi


